<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <PackageId>PokerEngine</PackageId>
    <Version>0.1.6</Version>
    <Authors>Dmitrii Gilev</Authors>

    <Description>
      A deterministic poker rules engine written in C#.
    </Description>

    <PackageTags>
      poker;texas-holdem;omaha;game-engine;cards
    </PackageTags>

    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>icon.png</PackageIcon>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>
      https://github.com/DGilev91/PokerEngine
    </RepositoryUrl>

    <PackageProjectUrl>
      https://github.com/DGilev91/PokerEngine
    </PackageProjectUrl>

    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>



  <ItemGroup>
    <None Include="..\assets\icon.png" Pack="true" PackagePath="icon.png" />
    <None Include="..\README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PokerEngine.Tests" />
  </ItemGroup>
</Project>